version: '3.8'

services:
    postgres:
        image: postgres:13
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_PORT: 5432
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data/

    backend:
        build:
            dockerfile: Dockerfile
            context: .
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - postgres

volumes:
    pg_data: